### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by plumface-gcc** [time007gc/miku#1]
- [ ] Add temperature, frequency/presence penalty, and max tokens sliders
- [ ] Add regenerate button
- [ ] Move the bot response textbox lower
- [ ] Fix prompt to be more similar to rokos
